function x = struct_2_boundary(struct)

    global venus_swing_by
    if venus_swing_by == 1
        x = [...
            struct.phase_marte, ...
            struct.phase_venus, ...
            struct.t_terra_venus, ...
            struct.t_venus_marte,  ...
            struct.theta_entrada_venus, ...
            struct.R_impulso, ...
            struct.theta_impulso_r, ...
            struct.magnitude_impulso, ...
            struct.theta_impulso_v, ...
            struct.theta_saida_venus, ...
            struct.t_swing_by_start, ...
            struct.t_swing_by_end ...
        ];
    else
        x = [...
            struct.phase_marte, ...
            struct.t_terra_marte ...
        ];
    end

end