function x = struct_2_boundary(struct)

x = [...
    struct.theta_oe_terra, ...
    struct.theta_soi_terra, ...
    struct.theta_soi_venus, ...
    struct.deflexao_venus, ...
    struct.phase_venus, ...
    struct.theta_soi_marte, ...
    struct.theta_oe_marte, ...
    struct.phase_marte, ...
    struct.t_oe_terra_soi_terra, ...
    struct.t_soi_terra_soi_venus, ...
    struct.t_soi_venus_soi_venus, ...
    struct.t_soi_venus_soi_marte, ...
    struct.t_soi_marte_oe_marte, ...
];

end