function x = struct_2_boundary(struct)

    global venus_swing_by
    if venus_swing_by == 1
        x = [...
            struct.phase_marte, ...
            struct.phase_venus, ...
            struct.t_terra_venus, ...
            struct.t_venus_marte,  ...
            struct.rp, ...
        ];
    else
        x = [...
            struct.phase_marte, ...
            struct.t_terra_marte ...
        ];
    end

end